name: Deploy Complex
on:
  push:
    branches:
      - main
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    #  Check out the code
      - uses: actions/checkout@v2
    #  Build the docker images
      - run: docker build -t pprofili/multi-client ./client
      - run: docker build -t pprofili/multi-nginx ./nginx
      - run: docker build -t pprofili/multi-server ./server
      - run: docker build -t pprofili/multi-worker ./worker

    #     Log into Docker Hub and push the images up there
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - run: docker push pprofili/multi-client
      - run: docker push pprofili/multi-nginx
      - run: docker push pprofili/multi-server
      - run: docker push pprofili/multi-worker
#      - run: docker run -e CI=true pprofili/docker-react npm test
 
      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'
 
      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v18
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: docker-react
          environment_name: Dockerreact-env
          existing_bucket_name: elasticbeanstalk-us-east-2-531322614867
          region: us-east-2
          version_label: ${{ github.sha }}
          deployment_package: deploy.zip